import ActiveLink from '@/src/components/ActiveLink/ActiveLink'
import Layout from '@/src/components/Layout/Layout'
import Head from 'next/head'
import { NextPage } from 'next'
import { ReactNode } from 'react'

export default function Home() {
    return (
        <>
            <Head>
                <title>Página de inicio</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <main className={`p-10`}>
                    <article className="mt-5">
                        <h1 className={`text-3xl font-bold text-gray-900`}>
                            Welcome to my personal blog...
                        </h1>
                        <p className={`text-md`}>Home page</p>
                    </article>
                </main>
            </Layout>
        </>
    )
}
