import Head from 'next/head'
//import Image from 'next/image'
import { Lato, Lobster_Two } from 'next/font/google'
//import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import GlobalStyle from '@/src/components/GlobalStyle'


const lobster = Lobster_Two({
  weight: [ "400", "700"],
  style: "normal",
  subsets: ["latin"],
  variable: '--font-lobster'
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <GlobalStyle />
      <main className="p-10">
        <p className={`text-md font-lobster`}>Página de início</p>
        <Link href={'/about/'} className='mr-5 underline'>
          Sobre
        </Link>
        <Link href={'/faq/'} className='underline mr-5'>
          FAQ
        </Link>
        <h1 className={`text-3xl font-bold text-gray-900`}>
          Bem-vindo site feito com next.js e react.js 
        </h1>
      </main>
    </>
  )
}
