import Head from 'next/head'
import Image from 'next/image'
import { Lato, Lobster_Two } from 'next/font/google'
import styles from '@/styles/Home.module.css'


const lobster = Lobster_Two({
  weight: [ "400", "700"],
  style: "normal",
  subsets: ["latin"],
  variable: '--font-lobster'
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <main>
        <p className={`text-md font-lobster underline`}>OI TUDO BEM</p>
        <h1 className={`text-3xl font-bold text-gray-900`}>
          Bem-vindo ao site de niko dev não somos 
        </h1>
      </main>
    </>
  )
}
